import "@angular/platform-browser";
import "@angular/platform-browser-dynamic";
import "@angular/core";
import "@angular/common";
import "@angular/http";
import "@angular/router";
import "rxjs";
import "node-uuid";
import "moment-timezone";
import "moment";
import "jquery";
import "eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js";
import "fullcalendar/dist/fullcalendar";
import "datatables.net";
import "datatables.net-bs";
import "bootstrap/dist/js/bootstrap";

require("!style!css!fullcalendar/dist/fullcalendar.css");
require("!style!css!eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css");
require("!style!css!datatables.net-bs/css/dataTables.bootstrap.css");
require("!style!css!bootstrap/dist/css/bootstrap.css");
require("!style!css!../styles/style.css");
require("!style!css!font-awesome/css/font-awesome.css");
